name: flutter_framework
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  cupertino_icons: ^1.0.8

  # State 管理
  flutter_riverpod: ^2.5.1
  # 路由
  go_router: ^14.1.0
  # 本地儲存
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # API / HTTP
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  # WebSocket
  web_socket_channel: ^3.0.0
  # WebView
  webview_flutter: ^4.4.2
  url_launcher: ^6.2.5
  # JSON 序列化
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  # Indicator
  smooth_page_indicator: ^1.1.0
  # Env
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - env/.env.dev
    - env/.env.uat
    - env/.env.prod
    - assets/
    - assets/resources/
    - assets/resources/splash/
    - assets/resources/introduction/

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: l10n.dart
  output-class: AppLocalizations
